- name: Test
  hosts: localhost
  vars_prompt:
   - name: target_disk
     prompt: "Enter disk to partition."
     private: no
  tasks:
   - name: test
     debug:
       msg:
         - "{{ target_disk }}"
